# Generated by Django 5.1.2 on 2024-11-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_empleado_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='curp',
        ),
    ]
